export const TIMERS_FETCH_DATA_SUCCESS = 'TIMERS_FETCH_DATA_SUCCESS'
export const TIMER_FETCH_DATA_SUCCESS = 'TIMER_FETCH_DATA_SUCCESS'
export const TIMERS_FETCH_DATA = 'TIMERS_FETCH_DATA'
export const START_TIMER = 'START_TIMER';
export const END_TIMER = 'END_TIMER';
export const TIMER_TICK = 'TIMER_TICK'
